### ISSUE TITLE
Tip: Dutch names

### ISSUE THREAD

**Issue by seriousme** [s-a/muenchhausen#4]
Hi,

nice project.

I noticed the [list of Dutch names](https://github.com/s-a/muenchhausen/blob/master/DataGenerator/names/nl.json) is rather small.
In case you want to expand on that:
- [Male Dutch names](https://nl.wiktionary.org/wiki/Categorie:Mannelijke_naam_in_het_Nederlands)
- [Female Dutch names](https://nl.wiktionary.org/wiki/Categorie:Vrouwelijke_naam_in_het_Nederlands)

This should work for nl_NL (Netherlands) and most likely also for nl_BE (Flanders)

A more generic list is available at: https://en.wikipedia.org/wiki/List_of_most_popular_given_names

Cheers,
Hans

**Comment by s-a** [comment]
:+1: You figured out a temporary file used by data generator. All final JSON data storages are in lib/18n folder.

This is my workflow to copy data from Wikipedia manual with Sublime Text 3.

1. Copy and paster namelist
2. `ctrl+h` to replace `^[A-Z]$` with `§` 
3. mark `§`  and press `alt+f3` and then delete 2 times.
4. `ctrl+a`, `ctrl+l`, `"`, `end`, `,`
5. `ctrl+a`, `[` 
6. Delete the last comma at the end of array

**Comment by s-a** [comment]
Dutch names availlable since `v0.0.9` 😺
